apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basic-quarkus-db.fullname" . }}
  labels:
    {{- include "basic-quarkus-db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "basic-quarkus-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "basic-quarkus-db.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "basic-quarkus-db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.env }}
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              {{- if $.Values.localPostgres.disabled }}
              value: jdbc:postgresql://{{ $.Release.Name }}-postgresql:5432/quarkus
              {{- else }}
              value: jdbc:postgresql://{{ include "basic-quarkus-db.fullname" $ }}-postgresql:5432/quarkus
              {{- end }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ tpl (toYaml .Values.image.repository) . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
