{{- range $key, $val := .Values }}
{{- if $val.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: openshift-gitops
  annotation:
    argocd.argoproj.io/sync-wave: "1"
  name: {{ $key }}
{{- end }}
{{- end }}